INSERT INTO listings (owner_id, title, description, price, category, sold_status, active_status)
VALUES
(12, 'New Pitchfork', 'Fresh from the blacksmith''s shop these pitchforks won''t leave you wanting. Move hay, pose with it in your yearly family photo, really show off your farming skills. \n Not intended for use as weapon.', 25, 'Farming', false, 'active', 'https://c8.alamy.com/comp/a5pwfj/farmer-holding-a-pitchfork-a5pwfj.jpg', false),
(12, 'Rusty Pitchfork', 'For the farmer who wants a pitchfork with a little more personality. You don''t want to get poked by this bad boy, espiecially since tetanus shots don''t exist. Limited quantities available.', 15, 'Farming', false, 'active', 'https://img0.etsystatic.com/076/0/10255754/il_fullxfull.816461934_1kze.jpg', false),
(9, 'Small Torch', 'Child sized torch, not too heavy. Made with the finest rags, sticks, and oil. Guaranteed burn time of 2 hours. Perfect to find your way through the village on those dark nights.', 10, 'Lighting', false, 'active', 'https://img-new.cgtrader.com/items/236634/medieval_torch_-_game_ready_-_has_emission_3d_model_fbx_ma_mb_obj_tga_7d8b5762-edb3-4501-8d8a-d217fd91f35b.jpg', false),
(9, 'Medium Torch', 'Mid sized torch. Guranteed burn time of 3 hours, but still light enough to swing around if needed. Casts bright light in a15ft radius and dim light for another 15ft.', 15, 'Lighting', false, 'active', 'http://preview.turbosquid.com/Preview/2016/05/04__05_38_41/Torch_wood_2.jpg97f95594-c23b-49d9-94b4-6bbd51684bedOriginal.jpg', false),
(9, 'Large Torch', 'Deluxe torch. Burn time of up to 4 hours. Casts bright light in a 20ft radius, and dim light for another 20ft. Villager must be strong enough to carry it.', 25, 'Lighting', false, 'active', 'https://static.turbosquid.com/Preview/2020/05/24__17_05_38/20.png26B1CECA-6724-4E26-8337-391FE764DB37DefaultHQ.jpg', false),
(10, 'Ripe Tomatoe', 'Unsold tomatoes, extra ripe. Very aerodynamic, squishy, with a strong aroma. Also available in crate format.', 1, 'Food', false, 'active', 'https://media.gq.com/photos/59303fb5fd48c3741bfc222b/16:9/pass/rotten-tomatoes-scores.jpg', false),
(10, 'Crate of Ripe Tomatoes', 'Best value for ripe tomatoes. If your village get-together needs to ''feed a crowd'', then this is the product for you. Crate contains up to 25 ripe tomatoes', 5, 'Food', false, 'active', 'https://thumbs.dreamstime.com/z/backgrounds-many-rotten-red-tomatoes-set-33855526.jpg', false),
(10, 'Hoe', 'Standard gardening equipment, and looks great in a photo. One size only.', 15, 'Farming', false, 'active', 'https://www.thedailygardener.com/wp-content/uploads/2019/05/Hoe-Tool.jpg'),
(9, 'Bale of Hay', 'Feeds up to 5 horses. Great for makeshift structures as well.', 2, 'Farming', false, 'active', 'https://www.remussanctuary.org/wp-content/uploads/2015/09/Hay-Bales.jpg', false),
(7, 'Re-Elect the Mayor Sign', 'Elegant and stylish addition to any property. Looks great in your front yard or in front of your shop.', 10, 'Misc', false, 'active', 'https://bannersigns.s3.amazonaws.com/IMESHSBUS1954_CUS.jpg', false),
(7, 'Snake Oil', 'All purpose remedy. Gets rid of common ailments, makes your crops grow larger, and even fights off the plague.', 30, 'Misc', false, 'active', 'https://first10em.b-cdn.net/wp-content/uploads/2019/06/Snake-Oil-Salesman.jpg', false)
(12, 'Hammer and Nails', 'Sturdy hammer and a pile of nails. Perfect for makeshift construction projects. ', 5, 'Farming', false, 'active', 'https://imgs.search.brave.com/o-FpR4R2V2nf_eUsQr3x_wm2isHx530-p1EaeGETNec/rs:fit:900:600:1/g:ce/aHR0cHM6Ly9pbWFn/ZXMuZmluZWFydGFt/ZXJpY2EuY29tL2lt/YWdlcy9hcnR3b3Jr/aW1hZ2VzL21lZGl1/bWxhcmdlLzEvdmlu/dGFnZS1oYW1tZXIt/YW5kLW5haWxzLWRv/bmFsZC1lcmlja3Nv/bi5qcGc', true)
(10, 'Wooden Planks', 'Nice reclaimed oak. Enough to build small apparatus.', 8, 'Farming', false, 'active', 'https://imgs.search.brave.com/JxEoCTW2wng6vV98jt4wVgqPAoSHGB1K_k8HIHA7pPg/rs:fit:1200:801:1/g:ce/aHR0cHM6Ly9jZG44/LmRpc3NvbHZlLmNv/bS9wL0Q5ODRfNDVf/NDQyL0Q5ODRfNDVf/NDQyXzEyMDAuanBn', true)
(12, 'Large Blade', 'Great for slicing', 15, 'Misc', false, 'https://imgs.search.brave.com/VknwksUSGyYKV0d1F9W_U5qO6iLUUpQb7mzeLuzD5Po/rs:fit:1200:1200:1/g:ce/aHR0cHM6Ly9pMS53/cC5jb20vYWdlb2Zy/ZXZvbHV0aW9uLm9y/Zy93cC1jb250ZW50/L3VwbG9hZHMvMjAx/NC8xMi9HdWlsbG90/aW5lTmF0aW9uYWxN/YXJpdGltZU11c2V1/bS5qcGc_Zml0PTE2/MDAlMkMxMjgwJnNz/bD0x', true)
(10, 'Hempen Rope', '1 Inch think, can support up to 100lbs. 50ft of length.', 3, 'Farming', false, 'https://imgs.search.brave.com/DPMruxk9twYEPzDAg4IO8aZ0s8A9L-_guLeZ1_vbX5Q/rs:fit:800:800:1/g:ce/aHR0cHM6Ly9jZG4u/c2hvcGlmeS5jb20v/cy9maWxlcy8xLzAw/NTAvMTI3NS8wNDQ3/L3Byb2R1Y3RzL0hl/bXAtUm9wZS1RdWFy/dGVyLUluY2hfUy0z/Mjk0X3dlYl9JTUdf/MDA3Nl84MDB4LkpQ/Rz92PTE1NDQ0NzM5/MjU', true)
;

