DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  is_admin BOOLEAN DEAFULT FALSE,
  registered_at DATE DEFAULT CURRENT_DATE,
);
